import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:flex">
          <div className="md:block hidden">
            <Sidebar />
          </div>
          <div className="ml-4 md:ml-36 lg:ml-80 mt-10">{children}</div>
          <div className="flex md:hidden">
            <Sidebar />
          </div>
        </div>
        {/* <div className="flex md:hidden"> */}
        {/* </div> */}
      </body>
    </html>
  );
}
